routes/web.php
<?php
use Illuminate\Support\Facades\Route;

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'as' => 'admin.'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'HomeController@getLogin']);
    Route::group(['before' => 'csrf'], function() {
        Route::post('login', ['as' => 'login', 'uses' => "HomeController@postLogin"]);
    });
    Route::group(['middleware' => 'admin'], function() {
        Route::post('images/upload', ['as' => 'images.upload', 'role' => 'backend', 'uses' => 'HomeController@uploadImage']);
        Route::get('', ['as' => 'home', 'uses' => 'HomeController@index']);
        Route::post('get-district-by-province', ['as' => 'get-district-by-province', 'uses' => 'HomeController@getDistrictByProvince']);

        Route::resource('fixed-assets', 'FixedAssetController');
        Route::post('fixed-assets/add-cost-item', ['as' => 'storeCostItem', 'uses' => 'FixedAssetController@storeCostItem']);
        Route::resource('fixed-asset-depreciation', 'FixedAssetDepreciationController');
        Route::post('fixed-asset-depreciation/get-info', ['as' => 'depreciation-month-year', 'uses' => 'FixedAssetDepreciationController@getMonthYear']);
        Route::post('fixed-asset-depreciation/get-debit-object', ['as' => 'get-debit-object', 'uses' => 'FixedAssetDepreciationController@getDebitObject']);
        Route::post('fixed-asset-depreciation/get-credit-object', ['as' => 'get-credit-object', 'uses' => 'FixedAssetDepreciationController@getCreditObject']);
        Route::get('fixed-asset-depreciation/{id}/save', ['as' => 'fixed-asset-depreciation.to-save', 'uses' => 'FixedAssetDepreciationController@toSave']);
        Route::post('fixed-asset-depreciation/{id}/save', ['as' => 'fixed-asset-depreciation.save', 'uses' => 'FixedAssetDepreciationController@save']);
        Route::resource('fixed-asset-disposal', 'FixedAssetDisposalController');
        Route::post('fixed-asset-disposal/get-asset-info', ['as' => 'get-asset-info', 'uses' => 'FixedAssetDisposalController@getAssetInfo']);
        Route::resource('fixed-asset-reports', 'FixedAssetReportController');
        Route::post('fixed-asset-reports/get-report', ['as' => 'get-report', 'uses' => 'FixedAssetReportController@getReport']);
        Route::get('fixed-asset-reports-export', ['as' => 'fixed-asset-export', 'uses' => 'FixedAssetReportController@exportExcel']);
       
        Route::resource('expenses-prepaid', 'ExpensesPrepaidController');
        Route::post('expenses-prepaid/get-voucher', ['as' => 'get-vouchers', 'uses' => 'ExpensesPrepaidController@getVouchers']);
        Route::post('expenses-prepaid/edit-voucher', ['as' => 'edit-voucher', 'uses' => 'ExpensesPrepaidController@editVouchers']);
        Route::post('expenses-prepaid/check-code', ['as' => 'check-code', 'uses' => 'ExpensesPrepaidController@checkCode']);
        Route::post('expenses-prepaid/search-vouchers', ['as' => 'search-vouchers', 'uses' => 'ExpensesPrepaidController@searchVouchers']);
        Route::post('expenses-prepaid-allocation/get-info', ['as' => 'expenses-prepaid-allocation', 'uses' => 'ExpensesPrepaidAllocationController@getMonthYear']);
        Route::post('expenses-prepaid-allocation/get-debit-object', ['as' => 'get-debit-object', 'uses' => 'ExpensesPrepaidAllocationController@getDebitObject']);
        Route::post('expenses-prepaid-allocation/get-credit-object', ['as' => 'get-credit-object', 'uses' => 'ExpensesPrepaidAllocationController@getCreditObject']);
        Route::resource('expenses-prepaid-allocation', 'ExpensesPrepaidAllocationController');

        Route::resource('cost-items', 'CostItemController');
        
        Route::resource('instrument-tool-types', 'InstrumentToolTypeController');
        Route::resource('instrument-tools', 'InstrumentToolController');
        Route::resource('instrument-tool-allocation', 'InstrumentToolAllocationController');
        Route::resource('instrument-tool-disposal', 'InstrumentToolDisposalController');
        Route::post('instrument-tool-disposal/get-info', ['as' => 'get-instrument-tool-info', 'uses' => 'InstrumentToolDisposalController@getInfo']);
        Route::post('instrument-tool-allocation/get-info', ['as' => 'instrument-tool-allocation', 'uses' => 'InstrumentToolAllocationController@getMonthYear']);
        
        Route::post('instrument-tools/add-type', ['as' => 'storeType', 'uses' => 'InstrumentToolController@storeType']);
        Route::get('accounts/get-parents', ['as' => 'accounts.get-parents', 'role' => ['admin.accounts.view'], 'uses' => 'AccountsController@getParents']);
        Route::get('accounts/get-by-id', ['as' => 'accounts.get-by-id', 'role' => ['admin.accounts.update'], 'uses' => 'AccountsController@getById']);
        Route::get('accounts/get-by-group', ['as' => 'accounts.get-by-group', 'role' => ['admin.accounts.create', 'admin.accounts.update'], 'uses' => 'AccountsController@getByGroup']);
        Route::get('ajax-callback', ['as' => 'cb', 'role' => 'backend', 'uses' => 'AccountsController@CallbackDebtAccount']);
        Route::resource('accounts', 'AccountsController');
        Route::resource('jobs', 'JobsController');
        Route::resource('payment-receip-bank-report', 'PayReBankReportController');
        Route::get('payment-receipt-vouchers/{id}/edit-payment-vendor', ['as' => 'payment-receipt-vouchers.edit-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editPaymentVendor']);
        // Route::get('payment-receipt-vouchers/get-info-object-2', ['as' => 'payment-receipt-vouchers.get-info-object-2', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getInforObject2']);
        Route::get('payment-receipt-vouchers/create-payment-order-bank', ['as' => 'payment-receipt-vouchers.create-payment-order', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentOrder']);
        Route::get('payment-receipt-vouchers/create-receipt-bank', ['as' => 'payment-receipt-vouchers.create-receipt-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createReceiptBank']);
        Route::post('payment-receipt-vouchers/store-receipt-bank', ['as' => 'payment-receipt-vouchers.store-receipt-payment-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@storeReceiptPaymentBank']);
        Route::get('payment-receipt-vouchers/edit-receipt-payment-bank/{id}', ['as' => 'payment-receipt-vouchers.edit-receipt-payment-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editReceiptPaymentBank']);
        Route::put('payment-receipt-vouchers/update-receipt-bank/{id}', ['as' => 'payment-receipt-vouchers.update-receipt-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@updateReceiptBank']);
        Route::put('payment-receipt-vouchers/update-payment-vendor/{id}', ['as' => 'payment-receipt-vouchers.update-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@updatePaymentVendor']);
        Route::post('payment-receipt-vouchers/get-voucher', ['as' => 'payment-receipt-vouchers.get-voucher', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getVoucher']);
        Route::get('payment-receipt-vouchers/{id}/edit-payment-vendor', ['as' => 'payment-receipt-vouchers.edit-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editPaymentVendor']);
        Route::get('payment-receipt-vouchers/create-payment-vendor-step2', ['as' => 'payment-receipt-vouchers.create-payment-vendor-step2', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentVendorStep_2']);
        Route::post('payment-receipt-vouchers/store-payment-vendor', ['as' => 'payment-receipt-vouchers.store-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@storePaymentVendor']);
        Route::get('payment-receipt-vouchers/get-service-voucher', ['as' => 'payment-receipt-vouchers.get-service-voucher', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getServiceVoucher']);
        Route::get('payment-receipt-vouchers/create-payment-vendor', ['as' => 'payment-receipt-vouchers.create-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentVendorStep_1']);
        Route::post('payment-receipt-vouchers/delete_all', ['as' => 'payment-receipt-vouchers.delete_all', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@delete_all']);
        Route::get('payment-receipt-vouchers/get-info-object', ['as' => 'payment-receipt-vouchers.get-info-object', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getInfoObject']);
        Route::get('payment-receipt-vouchers/create-receipt', ['as' => 'payment-receipt-vouchers.create-receipt', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@create_receipt']);
        Route::resource('payment-receipt-vouchers', 'PaymentReceiptVouchersController');
        Route::get('service-purchases/{id}/save', ['as' => 'service-purchases.save', 'role' => 'backend', 'uses' => 'ServicePurchasesController@save']); 
        Route::get('service-purchases/{id}/approve', ['as' => 'service-purchases.approve', 'role' => 'backend', 'uses' => 'ServicePurchasesController@approve']); 
        Route::get('service-purchases/{id}/cancel', ['as' => 'service-purchases.cancel', 'role' => 'backend', 'uses' => 'ServicePurchasesController@cancel']); 
        Route::get('service-purchases/get-info-sale-cost-item', ['as' => 'service-purchases.get-info-sale-cost-item', 'role' => 'backend', 'uses' => 'ServicePurchasesController@getInfoSaleCostItem']);
        Route::post('service-purchases/delete_all', ['as' => 'service-purchases.delete_all', 'role' => 'backend', 'uses' => 'ServicePurchasesController@delete_all']);
        Route::resource('service-purchases',"ServicePurchasesController");

app/Http/Controllers/Backend/BannerAdvertisementsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BannerAdvertisement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;

class BannerAdvertisementsController extends Controller
{
    public function index(Request $request)
    {
        $query = "1=1";
        $status = intval($request->input('status', -1));
        $type = trim($request->input('type'));
        if($status <> -1) $query .= " AND status = {$status}";
        if($type) $query .= " AND type = '{$type}'";
        $categories = BannerAdvertisement::whereRaw($query)->orderByRaw('updated_at DESC, type')->paginate(\App\Define\Constant::PAGE_NUM_20);
        return view('backend.banner-advertisements.index', compact('categories'));
    }

    public function create()
    {
        $types = \App\Define\Constant::getBannerTypes();
        return view('backend.banner-advertisements.create', compact('types'));
    }

    public function show($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'error');
            return redirect()->route('admin.banner-advertisements.index');
        }

        return view('backend.banner-advertisements.show', compact('category'));
    }

    public function edit($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'error');
            return redirect()->route('admin.banner-advertisements.index');
        }
        return view('backend.banner-advertisements.edit', compact('category'));
    }

    public function store(Request $request)
    {
        $request->merge(['status' => $request->input('status', 0)]);
        $validator = \Validator::make($data = $request->all(), BannerAdvertisement::rules());
        $validator->setAttributeNames(trans('banner_advertisements'));
        if ($validator->fails()) return back()->withErrors($validator)->withInput();
        $image  = $request->file('image');
        $ext    = pathinfo($image->getClientOriginalName(), PATHINFO_EXTENSION);
        $data['image'] = str_slug($data['name']) . '_' . time() . '.' . $ext;
        $image->move(config('upload.banner_advertisement'), $data['image']);
        $data['image'] = config('upload.banner_advertisement') . $data['image'];
        $data['created_by'] = $request->user()->id;
        BannerAdvertisement::create($data);
        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');

        return redirect()->route('admin.banner-advertisements.index');
    }

    public function update(Request $request, $id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'danger');
            return redirect()->route('admin.banner-advertisements.index');
        }
        $request->merge(['status' => $request->input('status', 0)]);
        $validator = \Validator::make($data = $request->all(), BannerAdvertisement::rules(intval($id)));//only(['status', 'name', 'seo_description', 'seo_keywords', 'image'])
        $validator->setAttributeNames(trans('banner_advertisements'));
        if ($validator->fails()) return back()->withErrors($validator)->withInput();

        if ($request->hasFile('image')) {
            if (\File::exists(public_path() . '/' . $category->image)) \File::delete(public_path() . '/' . $category->image);
            $image  = $request->file('image');
            $ext    = pathinfo($image->getClientOriginalName(), PATHINFO_EXTENSION);
            $data['image'] = str_slug($data['name']) . '_' . time(). '.' . $ext;
            $image->move(config('upload.banner_advertisement'), $data['image']);
            $data['image'] = config('upload.banner_advertisement') . $data['image'];
        }
        $category->update($data);
        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');

        return redirect()->route('admin.banner-advertisements.index');
    }

    public function destroy($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'danger');
            return redirect()->route('admin.banner-advertisements.index');
        }
        if (\File::exists(public_path() . '/' . $category->image)) \File::delete(public_path() . '/' . $category->image);
        $category->delete();

        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');
        return redirect()->route('admin.banner-advertisements.index');
    }
}

app/Http/Controllers/Backend/DemoController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Exports\DemoExport;
use App\Bank;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Session;

class DemoController 
{
    public function index(Request $request)
    {
        $banks = Bank::all();
        // dd(count($data['banks']));
       
        // for($i = 1; $i <= count($users); $i++){
        // foreach ($users as $key => $value) {
                      
        //             $a[] = "{" . '"recid"' . ":" . $i++ . "," . ltrim(json_encode($value), "{");
        //     }  
        //     $records = implode(",", $a);

        // }
        return view('backend.demo.demo1', compact('banks'));   
    }
    public function getData(){
        $banks = Bank::all();
        
        $records = [];
        foreach ($banks as $key => $value) {
            $record = [
                'id' => $value->id, 'name'=> $value->name
            ];
            $records[] = $record;
        }
        $data = [   
            'total' => -1,          
            'records' => $records
        ];    
        return response($data);
    }
    public function dataExport(){
        $banks = Bank::all();
        $abc = [
            [
                [
                    'text' => 'ID'
                ],
                [
                    'text' => 'Name'
                ]
            ]

        ];
        foreach ($banks as $key => $value) {
            $record = [
                [
                    'text' => $value->id
                ],
                [
                    'text' => $value->name
                ]
            ];
            $abc[] = $record;
        }
        $tableData = [[
            'sheetName' => 'Sheet1',
            'data' => $abc
        ]];
        $data = [   
            'option' => ['filename' => 'Export'],          
            'tableData' => $tableData
        ];    
        return response($data);
    }
    public function exportExcel(){
        return Excel::download(new DemoExport, 'Demo.xlsx'); 
    }
}

resources/views/backend/payment-receipt-vouchers/create.blade.php
@extends('backend.master')
@section('title')
    {!! trans('system.action.create') !!}-{!! App\Defines\PaymentReceiptVoucher::getTypeVouchers($type) !!}
@stop
@section('head')
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/iCheck/all.css') !!}"/>
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/select2/select2.min.css') !!}"/>
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/css/table.css') !!}"/>
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/bootstrap-datepicker/css/bootstrap-datepicker.css') !!}"/>
@section('content')
    <section class="content-header">
        <h1>
            {!! App\Defines\PaymentReceiptVoucher::getTypeVouchers($type) !!}
            <small>{!! trans('system.action.create') !!}</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="{!! route('admin.home') !!}">{!! trans('system.home') !!}</a></li>
            {{-- <li><a href="{!! route('admin.payment-receipt-vourchers.index') !!}">{!! trans('payment-vourchers.label') !!}</a></li> --}}
        </ol>
    </section>

    @if($errors->count())
        <div class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <h4><i class="icon fa fa-warning"></i> {!! trans('messages.error') !!}</h4>
            <ul>
                @foreach($errors->all() as $message)
                <li>{!! $message !!}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <section class="content overlay">
        {!! Form::open(['url' => route('admin.payment-receipt-vouchers.store'),'role' => 'form']) !!}
        {!! Form::hidden('type', $type) !!}
            <div class="row">
                <div class="col-md-12">
                    <div class="box box-default">
                        <div class="box-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-1">
                                           <b>{!! trans('payment_receipt_vouchers.object') !!}</b> 
                                        </div>
                                        <div class="col-md-2">
                                            {!! Form::select ('object', [' '=> trans('system.dropdown_choice')] + $partnerVendorCodes, old('object'), ['class' => 'form-control select2', 'required']) !!} 
                                        </div>                                       
                                        <div class="col-md-5">
                                            {!! Form::text('object_name', old('object_name'), ['class' => 'form-control', 'maxlength' => 20, 'required']) !!}                                    
                                        </div>
                                        <div class="col-md-1 text-right vcenter">
                                            <b>{!! trans('payment_receipt_vouchers.voucher_date') !!}</b>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="input-group">
                                                <div class="input-group-addon">
                                                    <i class="fa fa-calendar"></i>
                                                </div>
                                                {!! Form::text('date_vouchers', old('date_vouchers', date('d/m/Y')), ['class' => 'form-control date', 'placeholder' => 'MM/DD/YYYY', 'required']) !!}
                                            </div>
                                        </div>
                                    </div>
                                    <br>
                                    <div class="row">
                                        <div class="col-md-1">
                                          <b>{!! trans('payment_receipt_vouchers.beneficiary') !!}</b> 
                                        </div>
                                        <div class="col-md-7">
                                            {!! Form::text('beneficiary', old('beneficiary'), ['class' => 'form-control ']) !!}
                                        </div>
                                        <div class="col-md-1 text-right vcenter">
                                            <b>{!! trans('payment_receipt_vouchers.voucher_no') !!}</b>
                                        </div>
                                        <div class="col-md-3">
                                            {!! Form::text('voucher_no', old('voucher_no', $trx_no), ['class' => 'form-control', 'required']) !!}
                                        </div>
                                    </div>
                                    <br/>
                                    <div class="row">
                                        <div class="col-md-1">
                                            <b>{!! trans('payment_receipt_vouchers.address') !!}</b>
                                        </div>
                                        <div class="col-md-7">
                                            {!! Form::text('address', old('address'), ['class' => 'form-control']) !!}
                                        </div>
                                        <div class="col-md-1 text-right vcenter">
                                            <b>{!! trans('payment_receipt_vouchers.currency') !!}</b>
                                        </div>
                                        <div class="col-md-1">
                                            {!! Form::select('currency', [' '=> trans('system.dropdown_choice')] + $currency, old('currency'), ['class' => 'form-control select2', 'required']) !!}
                                        </div>
                                        <div class="col-md-1 text-right vcenter">
                                            <b>{!! trans('payment_receipt_vouchers.exchange_rate') !!}</b>
                                        </div>
                                        <div class="col-md-1">
                                            {!! Form::text('exchange_rate',  old('exchange_rate'), ['class' => 'form-control currency']) !!}
                                        </div>
                                    </div>
                                    <br/>
                                    <div class="row">
                                        <div class="col-md-1">
                                            <b>{!! trans('payment_receipt_vouchers.details') !!}</b>
                                        </div>
                                        <div class="col-md-7">
                                            {!! Form::text('details', old('details'), ['class' => 'form-control']) !!}
                                        </div>
                                    </div>
                                    <br/>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#tab_1" data-toggle="tab"><b>{!! trans('accounting.label') !!}</b></a></li>
                  <li><a href="#tab_2" data-toggle="tab"><b>{!! trans('taxes.label') !!}</b></a></li>
                </ul>
                <div class="tab-content">
                  <div class="tab-pane active" id="tab_1">
                    @include('backend.payment-receipt-vouchers.accounting')
                  </div>
                  <div class="tab-pane" id="tab_2">
                    @include('backend.payment-receipt-vouchers.tax')
                  </div>
                </div>
            </div>   
            <div class="row">
                <div class="col-md-12">
                    <div class="box">
                        <div class="box-body">
                            <table class='table borderless'>
                                <tr>
                                    <td style="text-align:center" colspan="2">
                                        {!! Form::checkbox('status', 1, old('status', 1), [ 'class' => 'minimal' ]) !!}
                                        {!! trans('system.status.active') !!}
                                    </td>
                                </tr>
                                <tr>
                                    <td colspan="2" class="text-center">
                                        {!! HTML::link(route( 'admin.payment-receipt-vouchers.index' ), trans('system.action.cancel'), ['class' => 'btn btn-danger btn-flat']) !!}
                                        {!! Form::submit(trans('system.action.save'), ['class' => 'btn btn-primary btn-flat']) !!}
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {!! Form::close() !!}
        </section>
@stop
@section('footer')
    <style>
        .vendor-dropdown {
            width: 800px !important;
        }

        .custom-dropdown {
            width: 500px !important;
            left: -350px !important;
        }
    </style>
    <script src="{!! asset('assets/backend/plugins/select2/select2.full.min.js') !!}"></script>
    <script src="{!! asset('assets/backend/plugins/iCheck/icheck.min.js') !!}"></script>
    <script src="{!! asset('assets/backend/plugins/moment/min/moment-with-locales.min.js') !!}"></script>
    <script src="{!! asset('assets/backend/plugins/input-mask/jquery.inputmask.min.js') !!}"></script>
    <script src="{!! asset('assets/backend/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js') !!}"></script>
    <script src="{!! asset('assets/backend/plugins/bootstrap-datepicker/locales/bootstrap-datepicker.vi.min.js') !!}"></script>
    <script src="{!! asset('assets/backend/js/fix-tabindex.js') !!}"></script>
    <script src="{!! asset('assets/backend/js/call-plugins.js') !!}"></script>
    <script src="{!! asset('assets/backend/js/payment-receipt-voucher.js') !!}"></script>
    <script src="{!! asset('assets/backend/js/select2-table-partner.js') !!}"></script>
    <script>
        var trans = @json(trans("service_purchases.buy_service_of"));
        callICheck();
        callInputMaskDecimal();
    </script>
    <script>
        !function ($) {
            $(function() {
                enterTab();
                select2Tab();
                renderTableS2('select[name="object"]', "{!! route('admin.partners.get-all-partner') !!}", 'vendor-dropdown', s2FormatResultPartner, setInfoObjectOriginal);
                renderTableS2('select[name="object_code_tax[]"]', "{!! route('admin.partners.get-all-partner') !!}", 'custom-dropdown', s2FormatResultPartner, getInfoTax);
                renderTableS2('select[name="object_code_accounting[]"]', "{!! route('admin.partners.get-all-partner') !!}", 'custom-dropdown', s2FormatResultPartner, setInfoObjectAccounting);
                renderTableS2('select[name="bank_account[]"]', "{!! route('admin.banks.get-info-bank-account') !!}", 'custom-dropdown', s2FormatResultAccount);
            });
        }(window.jQuery);
    </script>
@stop

resources/views/backend/payment-receipt-vouchers/row-accounting.blade.php
<tr>
    <td style="white-space: nowrap; vertical-align: middle; text-align: center;">
        <p style="vertical-align: middle; text-align: center;">
            <a tabindex="-1" href="javascript:void(0);" title="{!! trans('input_invoices.copy_current_row') !!}" class="text-success clone-row-accounting"><i class="fas fa-copy"></i></a>
            &nbsp;&nbsp;
            <a tabindex="-1" href="javascript:void(0);" title="{!! trans('input_invoices.remove_current_row') !!}" class="text-danger remove-row-accounting"><i class="fas fa-minus"></i></a>
        </p>
    </td>
    <td style="white-space: nowrap; min-width: 120px;">
        {!! Form::text('description[]', old('description[]'), ['class' => 'form-control']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::select('job_code[]', [' '=> trans('system.dropdown_choice')] + $jobs, old('job_code[]'), ['class' => 'form-control select2']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::select('debit_account[]', [' '=> trans('system.dropdown_choice')] + $accounts, old('debit_account[]'), ['class' => 'form-control select2']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::select('credit_account[]', [' '=> trans('system.dropdown_choice')] + $accounts, old('credit_account[]'), ['class' => 'form-control select2']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 200px;">
        {!! Form::text('amount[]', old('amount[]'), ['class' => 'form-control currency']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 200px;">
        {!! Form::text('exchange[]', old('exchange[]'), ['class' => 'form-control currency']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::select('branch_code[]', [' '=> trans('system.dropdown_choice')] + $branchCodes, old('branch_code[]'), ['class' => 'form-control select2']) !!}
    </td>   
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::select('object_code[]', [' '=> trans('system.dropdown_choice')] + $partnerVendorCodes, old('object_code[]'), ['class' => 'form-control select2']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::text('object_name[]', old('object_name[]'), ['class' => 'form-control']) !!}
    </td>
    <td style="white-space: nowrap; min-width: 150px;">
        {!! Form::select('bank_account[]', [' '=> trans('system.dropdown_choice')], old('bank_account[]'), ['class' => 'form-control select2']) !!}
    </td>
</tr>