routes/web.php
<?php
use Illuminate\Support\Facades\Route;

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'as' => 'admin.'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'HomeController@getLogin']);
    Route::group(['before' => 'csrf'], function() {
        Route::post('login', ['as' => 'login', 'uses' => "HomeController@postLogin"]);
    });
    Route::group(['middleware' => 'admin'], function() {
        Route::post('images/upload', ['as' => 'images.upload', 'role' => 'backend', 'uses' => 'HomeController@uploadImage']);
        Route::get('', ['as' => 'home', 'uses' => 'HomeController@index']);
        Route::post('get-district-by-province', ['as' => 'get-district-by-province', 'uses' => 'HomeController@getDistrictByProvince']);

        Route::resource('fixed-assets', 'FixedAssetController');
        Route::post('fixed-assets/add-cost-item', ['as' => 'storeCostItem', 'uses' => 'FixedAssetController@storeCostItem']);
        Route::resource('fixed-asset-depreciation', 'FixedAssetDepreciationController');
        Route::post('fixed-asset-depreciation/get-info', ['as' => 'depreciation-month-year', 'uses' => 'FixedAssetDepreciationController@getMonthYear']);
        Route::post('fixed-asset-depreciation/get-debit-object', ['as' => 'get-debit-object', 'uses' => 'FixedAssetDepreciationController@getDebitObject']);
        Route::post('fixed-asset-depreciation/get-credit-object', ['as' => 'get-credit-object', 'uses' => 'FixedAssetDepreciationController@getCreditObject']);
        Route::get('fixed-asset-depreciation/{id}/save', ['as' => 'fixed-asset-depreciation.to-save', 'uses' => 'FixedAssetDepreciationController@toSave']);
        Route::post('fixed-asset-depreciation/{id}/save', ['as' => 'fixed-asset-depreciation.save', 'uses' => 'FixedAssetDepreciationController@save']);
        Route::resource('fixed-asset-disposal', 'FixedAssetDisposalController');
        Route::post('fixed-asset-disposal/get-asset-info', ['as' => 'get-asset-info', 'uses' => 'FixedAssetDisposalController@getAssetInfo']);
        Route::resource('fixed-asset-reports', 'FixedAssetReportController');
        Route::post('fixed-asset-reports/get-report', ['as' => 'get-report', 'uses' => 'FixedAssetReportController@getReport']);
        Route::get('fixed-asset-reports-export', ['as' => 'fixed-asset-export', 'uses' => 'FixedAssetReportController@exportExcel']);
       
        Route::resource('expenses-prepaid', 'ExpensesPrepaidController');
        Route::post('expenses-prepaid/get-voucher', ['as' => 'get-vouchers', 'uses' => 'ExpensesPrepaidController@getVouchers']);
        Route::post('expenses-prepaid/edit-voucher', ['as' => 'edit-voucher', 'uses' => 'ExpensesPrepaidController@editVouchers']);
        Route::post('expenses-prepaid/check-code', ['as' => 'check-code', 'uses' => 'ExpensesPrepaidController@checkCode']);
        Route::post('expenses-prepaid/search-vouchers', ['as' => 'search-vouchers', 'uses' => 'ExpensesPrepaidController@searchVouchers']);
        Route::post('expenses-prepaid-allocation/get-info', ['as' => 'expenses-prepaid-allocation', 'uses' => 'ExpensesPrepaidAllocationController@getMonthYear']);
        Route::post('expenses-prepaid-allocation/get-debit-object', ['as' => 'get-debit-object', 'uses' => 'ExpensesPrepaidAllocationController@getDebitObject']);
        Route::post('expenses-prepaid-allocation/get-credit-object', ['as' => 'get-credit-object', 'uses' => 'ExpensesPrepaidAllocationController@getCreditObject']);
        Route::resource('expenses-prepaid-allocation', 'ExpensesPrepaidAllocationController');

        Route::resource('cost-items', 'CostItemController');
        
        Route::resource('instrument-tool-types', 'InstrumentToolTypeController');
        Route::resource('instrument-tools', 'InstrumentToolController');
        Route::resource('instrument-tool-allocation', 'InstrumentToolAllocationController');
        Route::resource('instrument-tool-disposal', 'InstrumentToolDisposalController');
        Route::post('instrument-tool-disposal/get-info', ['as' => 'get-instrument-tool-info', 'uses' => 'InstrumentToolDisposalController@getInfo']);
        Route::post('instrument-tool-allocation/get-info', ['as' => 'instrument-tool-allocation', 'uses' => 'InstrumentToolAllocationController@getMonthYear']);
        
        Route::post('instrument-tools/add-type', ['as' => 'storeType', 'uses' => 'InstrumentToolController@storeType']);
        Route::get('accounts/get-parents', ['as' => 'accounts.get-parents', 'role' => ['admin.accounts.view'], 'uses' => 'AccountsController@getParents']);
        Route::get('accounts/get-by-id', ['as' => 'accounts.get-by-id', 'role' => ['admin.accounts.update'], 'uses' => 'AccountsController@getById']);
        Route::get('accounts/get-by-group', ['as' => 'accounts.get-by-group', 'role' => ['admin.accounts.create', 'admin.accounts.update'], 'uses' => 'AccountsController@getByGroup']);
        Route::get('ajax-callback', ['as' => 'cb', 'role' => 'backend', 'uses' => 'AccountsController@CallbackDebtAccount']);
        Route::resource('accounts', 'AccountsController');
        Route::resource('jobs', 'JobsController');
        Route::resource('payment-receip-bank-report', 'PayReBankReportController');
        Route::get('payment-receipt-vouchers/{id}/edit-payment-vendor', ['as' => 'payment-receipt-vouchers.edit-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editPaymentVendor']);
        // Route::get('payment-receipt-vouchers/get-info-object-2', ['as' => 'payment-receipt-vouchers.get-info-object-2', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getInforObject2']);
        Route::get('payment-receipt-vouchers/create-payment-order-bank', ['as' => 'payment-receipt-vouchers.create-payment-order', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentOrder']);
        Route::get('payment-receipt-vouchers/create-receipt-bank', ['as' => 'payment-receipt-vouchers.create-receipt-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createReceiptBank']);
        Route::post('payment-receipt-vouchers/store-receipt-bank', ['as' => 'payment-receipt-vouchers.store-receipt-payment-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@storeReceiptPaymentBank']);
        Route::get('payment-receipt-vouchers/edit-receipt-payment-bank/{id}', ['as' => 'payment-receipt-vouchers.edit-receipt-payment-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editReceiptPaymentBank']);
        Route::put('payment-receipt-vouchers/update-receipt-bank/{id}', ['as' => 'payment-receipt-vouchers.update-receipt-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@updateReceiptBank']);
        Route::put('payment-receipt-vouchers/update-payment-vendor/{id}', ['as' => 'payment-receipt-vouchers.update-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@updatePaymentVendor']);
        Route::post('payment-receipt-vouchers/get-voucher', ['as' => 'payment-receipt-vouchers.get-voucher', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getVoucher']);
        Route::get('payment-receipt-vouchers/{id}/edit-payment-vendor', ['as' => 'payment-receipt-vouchers.edit-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editPaymentVendor']);
        Route::get('payment-receipt-vouchers/create-payment-vendor-step2', ['as' => 'payment-receipt-vouchers.create-payment-vendor-step2', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentVendorStep_2']);
        Route::post('payment-receipt-vouchers/store-payment-vendor', ['as' => 'payment-receipt-vouchers.store-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@storePaymentVendor']);
        Route::get('payment-receipt-vouchers/get-service-voucher', ['as' => 'payment-receipt-vouchers.get-service-voucher', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getServiceVoucher']);
        Route::get('payment-receipt-vouchers/create-payment-vendor', ['as' => 'payment-receipt-vouchers.create-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentVendorStep_1']);
        Route::post('payment-receipt-vouchers/delete_all', ['as' => 'payment-receipt-vouchers.delete_all', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@delete_all']);
        Route::get('payment-receipt-vouchers/get-info-object', ['as' => 'payment-receipt-vouchers.get-info-object', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getInfoObject']);
        Route::get('payment-receipt-vouchers/create-receipt', ['as' => 'payment-receipt-vouchers.create-receipt', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@create_receipt']);
        Route::resource('payment-receipt-vouchers', 'PaymentReceiptVouchersController');
        Route::get('service-purchases/{id}/save', ['as' => 'service-purchases.save', 'role' => 'backend', 'uses' => 'ServicePurchasesController@save']); 
        Route::get('service-purchases/{id}/approve', ['as' => 'service-purchases.approve', 'role' => 'backend', 'uses' => 'ServicePurchasesController@approve']); 
        Route::get('service-purchases/{id}/cancel', ['as' => 'service-purchases.cancel', 'role' => 'backend', 'uses' => 'ServicePurchasesController@cancel']); 
        Route::get('service-purchases/get-info-sale-cost-item', ['as' => 'service-purchases.get-info-sale-cost-item', 'role' => 'backend', 'uses' => 'ServicePurchasesController@getInfoSaleCostItem']);
        Route::post('service-purchases/delete_all', ['as' => 'service-purchases.delete_all', 'role' => 'backend', 'uses' => 'ServicePurchasesController@delete_all']);
        Route::resource('service-purchases',"ServicePurchasesController");

app/Http/Controllers/Backend/BannerAdvertisementsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BannerAdvertisement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;

class BannerAdvertisementsController extends Controller
{
    public function index(Request $request)
    {
        $query = "1=1";
        $status = intval($request->input('status', -1));
        $type = trim($request->input('type'));
        if($status <> -1) $query .= " AND status = {$status}";
        if($type) $query .= " AND type = '{$type}'";
        $categories = BannerAdvertisement::whereRaw($query)->orderByRaw('updated_at DESC, type')->paginate(\App\Define\Constant::PAGE_NUM_20);
        return view('backend.banner-advertisements.index', compact('categories'));
    }

    public function create()
    {
        $types = \App\Define\Constant::getBannerTypes();
        return view('backend.banner-advertisements.create', compact('types'));
    }

    public function show($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'error');
            return redirect()->route('admin.banner-advertisements.index');
        }

        return view('backend.banner-advertisements.show', compact('category'));
    }

    public function edit($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'error');
            return redirect()->route('admin.banner-advertisements.index');
        }
        return view('backend.banner-advertisements.edit', compact('category'));
    }

    public function store(Request $request)
    {
        $request->merge(['status' => $request->input('status', 0)]);
        $validator = \Validator::make($data = $request->all(), BannerAdvertisement::rules());
        $validator->setAttributeNames(trans('banner_advertisements'));
        if ($validator->fails()) return back()->withErrors($validator)->withInput();
        $image  = $request->file('image');
        $ext    = pathinfo($image->getClientOriginalName(), PATHINFO_EXTENSION);
        $data['image'] = str_slug($data['name']) . '_' . time() . '.' . $ext;
        $image->move(config('upload.banner_advertisement'), $data['image']);
        $data['image'] = config('upload.banner_advertisement') . $data['image'];
        $data['created_by'] = $request->user()->id;
        BannerAdvertisement::create($data);
        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');

        return redirect()->route('admin.banner-advertisements.index');
    }

    public function update(Request $request, $id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'danger');
            return redirect()->route('admin.banner-advertisements.index');
        }
        $request->merge(['status' => $request->input('status', 0)]);
        $validator = \Validator::make($data = $request->all(), BannerAdvertisement::rules(intval($id)));//only(['status', 'name', 'seo_description', 'seo_keywords', 'image'])
        $validator->setAttributeNames(trans('banner_advertisements'));
        if ($validator->fails()) return back()->withErrors($validator)->withInput();

        if ($request->hasFile('image')) {
            if (\File::exists(public_path() . '/' . $category->image)) \File::delete(public_path() . '/' . $category->image);
            $image  = $request->file('image');
            $ext    = pathinfo($image->getClientOriginalName(), PATHINFO_EXTENSION);
            $data['image'] = str_slug($data['name']) . '_' . time(). '.' . $ext;
            $image->move(config('upload.banner_advertisement'), $data['image']);
            $data['image'] = config('upload.banner_advertisement') . $data['image'];
        }
        $category->update($data);
        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');

        return redirect()->route('admin.banner-advertisements.index');
    }

    public function destroy($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'danger');
            return redirect()->route('admin.banner-advertisements.index');
        }
        if (\File::exists(public_path() . '/' . $category->image)) \File::delete(public_path() . '/' . $category->image);
        $category->delete();

        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');
        return redirect()->route('admin.banner-advertisements.index');
    }
}

app/Http/Controllers/Backend/DemoController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Exports\DemoExport;
use App\Bank;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Session;

class DemoController 
{
    public function index(Request $request)
    {
        $banks = Bank::all();
        // dd(count($data['banks']));
       
        // for($i = 1; $i <= count($users); $i++){
        // foreach ($users as $key => $value) {
                      
        //             $a[] = "{" . '"recid"' . ":" . $i++ . "," . ltrim(json_encode($value), "{");
        //     }  
        //     $records = implode(",", $a);

        // }
        return view('backend.demo.demo1', compact('banks'));   
    }
    public function getData(){
        $banks = Bank::all();
        
        $records = [];
        foreach ($banks as $key => $value) {
            $record = [
                'id' => $value->id, 'name'=> $value->name
            ];
            $records[] = $record;
        }
        $data = [   
            'total' => -1,          
            'records' => $records
        ];    
        return response($data);
    }
    public function dataExport(){
        $banks = Bank::all();
        $abc = [
            [
                [
                    'text' => 'ID'
                ],
                [
                    'text' => 'Name'
                ]
            ]

        ];
        foreach ($banks as $key => $value) {
            $record = [
                [
                    'text' => $value->id
                ],
                [
                    'text' => $value->name
                ]
            ];
            $abc[] = $record;
        }
        $tableData = [[
            'sheetName' => 'Sheet1',
            'data' => $abc
        ]];
        $data = [   
            'option' => ['filename' => 'Export'],          
            'tableData' => $tableData
        ];    
        return response($data);
    }
    public function exportExcel(){
        return Excel::download(new DemoExport, 'Demo.xlsx'); 
    }
}

resources/views/backend/fixed-asset-disposal/index.blade.php
@extends('backend.master')
@section('title')
{!! trans('system.action.list') !!} {!! trans('menus.fixed-asset-depreciation.label') !!}
@stop
@section('head')
<script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/daterangepicker/daterangepicker.css') !!}" />
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/iCheck/all.css') !!}" />
    <link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/select2/select2.min.css') !!}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/3.2.6/jquery.inputmask.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
@stop
@section('content')
<section class="content-header">
    <h1>
        {!! trans('menus.fixed-asset-disposal.label') !!}
        <small>{!! trans('system.action.list') !!}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{!! route('admin.home') !!}">{!! trans('system.home') !!}</a></li>
        <li><a href="{!! route('admin.fixed-asset-depreciation.index') !!}">{!! trans('menus.fixed-asset-disposal.label') !!}</a></li>
    </ol>
</section>
<section class="content overlay">
<div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">{!! trans('system.action.filter') !!}</h3>
            <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
            </div>
        </div>
        <div class="box-body">
            {!! Form::open([ 'url' => route('admin.fixed-asset-disposal.index'), 'method' => 'GET', 'role' => 'search' ]) !!}
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        {!! Form::label('from', trans('system.from')) !!}
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            {!! Form::text('from_date', Request::input('from_date'), ['class' => 'form-control pull-right date_picker']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        {!! Form::label('to', trans('system.to')) !!}
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            {!! Form::text('to_date', Request::input('to_date'), ['class' => 'form-control pull-right date_picker']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        {!! Form::label('status', trans('system.status.label')) !!}
                        {!! Form::select('status', ['' => trans('system.dropdown_choice')] + App\Defines\FixedAssetDepreciation::getStatusForOption(), Request::input('status'), ['class' => 'form-control select2'])!!}
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group">
                        {!! Form::label('filter', trans('system.action.label'), ['style' => 'display: block;']) !!}
                        <button type="submit" class="btn btn-default btn-flat" style="display: block;">
                            <span class="glyphicon glyphicon-search"></span>&nbsp; {!! trans('system.action.search') !!}
                        </button>
                    </div>
                </div>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
    <div class="row" style="display: flex;">
        <div class="col-sm-1" style="margin-right: 3px;">
            <a href="{!! route('admin.fixed-asset-disposal.create') !!}" class='btn btn-primary btn-flat'>
                <span class="glyphicon glyphicon-plus"></span>&nbsp; {!! trans('system.action.create') !!}
            </a>
        </div>
        <div class="col-sm-12 pull-right">
            <span class="pull-right">
                {!! $disposals->appends( Request::except('page') )->render() !!}
            </span>
            <span class="pull-right">
                {!! Form::select('page_num', [ 10 => trans('system.show') . ' 10' . trans('system.items'), 20 => trans('system.show') . ' 20' . trans('system.items'), 50 => trans('system.show') . ' 50' . trans('system.items') , 100 => trans('system.show') . ' 100' . trans('system.items'), 500 => trans('system.show') . ' 500' . trans('system.items') ], Request::input('page_num', 20), ['class' => 'form-control select2']) !!}
            </span>
        </div>
    </div>
    @if (count($disposals) > 0)
    <?php $labels = ['default', 'success', 'info', 'danger', 'warning']; ?>
    <div class="box">
        <div class="box-header">
            <?php $i = (($disposals->currentPage() - 1) * $disposals->perPage()) + 1; ?>
            <div class="form-inline">
                <div class="form-group">
                    {!! trans('system.show_from') !!} {!! $i . ' ' . trans('system.to') . ' ' . ($i - 1 + $disposals->count()) . ' ( ' . trans('system.total') . ' ' . $disposals->total() . ' )' !!}
                </div>
            </div>
        </div>
        <div class="box-body no-padding">
            <div class="table-responsive">
                <table class="table table-bordered table-striped" style="border-collapse: collapse;">
                    <thead style="background: #3C8DBC; color: white;">
                        <tr>
                            <th style="text-align: center; vertical-align: middle;">{!! trans('fixed_asset_depreciation.voucher_date') !!}</th>
                            <th style="text-align: center; vertical-align: middle;">{!! trans('fixed_asset_depreciation.voucher_number') !!}</th>
                            <th style="text-align: center; vertical-align: middle;">{!! trans('fixed_asset_disposal.disposal_reason') !!}</th>
                            <th style="text-align: center; vertical-align: middle;">{!! trans('fixed_asset_depreciation.money_amount') !!}</th>
                            <th style="text-align: center; vertical-align: middle;"> {!! trans('system.status.label') !!}</th>
                            <th style="text-align: center; vertical-align: middle;"> {!! trans('system.action.label') !!} </th>
                        </tr>
                    </thead>
                    <tbody class="borderless">
                        @foreach ($disposals as $item)
                            <tr class="treegrid-{!! $item->id !!}">
                                <td style="text-align: center; vertical-align: middle;">
                                    {!! date_format(date_create($item->voucher_date), "d/m/Y") !!}
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    <a href="{!! route('admin.fixed-asset-disposal.show', $item->id) !!}">{!! $item->voucher_number !!}</a>
                                </td>
                                <td style="vertical-align: middle;">
                                    {!! $item->disposal_reason !!}
                                </td>
                                <td style="text-align: right; vertical-align: middle;">
                                    {!! number_format(App\Models\FixedAssetDisposal::getTotal($item->id)) !!}
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    @if($item->status == "DRAFT")
                                        <span class="label label-danger">{!! trans('system.status.draft') !!}</span>
                                    @elseif($item->status == "SAVE")
                                        <span class="label label-primary">{!! trans('system.status.save') !!}</span>
                                    @elseif($item->status == "APPROVED")
                                        <span class="label label-success">{!! trans('system.status.approved') !!}</span>
                                    @endif
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    @if($item->status == "DRAFT" && $item->created_by == session('created_by'))
                                        
                                        <a href="{!! route('admin.fixed-asset-disposal.edit', $item->id) !!}" class="btn btn-xs btn-default" title="{!! trans('system.action.edit') !!}">
                                            <i class="text-warning glyphicon glyphicon-edit"></i>
                                        </a>
                                        &nbsp;
                                        <a href="javascript:void(0)" link="{!! route('admin.fixed-asset-disposal.destroy', $item->id) !!}" class="btn-confirm-del btn btn-default btn-xs" title="{!! trans('system.action.delete') !!}">
                                            <i class="text-danger glyphicon glyphicon-remove"></i>
                                    </a>
                                    @elseif($item->status == "SAVE" && $item->created_by == session('created_by'))
                                        <a href="{!! route('admin.fixed-asset-depreciation.save', $item->id) !!}" class="btn btn-xs btn-default" title="{!! trans('system.action.approve') !!}">
                                            <i class="text-success glyphicon glyphicon-floppy-saved"></i>
                                        </a>
                                    @else
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @else
    <div class="alert alert-info"> {!! trans('system.no_record_found') !!}</div>
    @endif
</section>
@stop
@section('footer')
<script src="{!! asset('assets/backend/plugins/iCheck/icheck.min.js') !!}"></script>
<link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/iCheck/all.css') !!}" />
<script src="{!! asset('assets/backend/plugins/select2/select2.full.min.js') !!}"></script>
<script src="{!! asset('assets/backend/plugins/daterangepicker/moment.min.js') !!}"></script>
<script src="{!! asset('assets/backend/plugins/moment/min/moment-with-locales.min.js') !!}"></script>
<script src="{!! asset('assets/backend/plugins/input-mask/jquery.inputmask.min.js') !!}"></script>
<script>   
    $('.date_picker').daterangepicker({
        "locale": {
            "format": "DD/MM/YYYY",
        },
        autoUpdateInput:false,
        singleDatePicker: true,
        showDropdowns: true,
        }, function(start, end, label) {       
    });
    $('.date_picker').on('apply.daterangepicker', function (ev, picker) {
        $(this).val(picker.startDate.format('DD/MM/YYYY'));
    });
</script>
<script>
        !function ($) {
            $(function() {
                $(".select2").select2({ width: '100%' });
                $("select[name='page_num']").change(function(event) {
                    onReload('page_num', $(this).val());
                });
            });
        }(window.jQuery);
        function onReload ($key, $value) {
            var queryParameters = {}, queryString = location.search.substring(1),
                re = /([^&=]+)=([^&]*)/g, m;
            while (m = re.exec(queryString)) {
                queryParameters[decodeURIComponent(m[1])] = decodeURIComponent(m[2]);
            }
            queryParameters[$key]   = $value;
            queryParameters['page'] = 1;
            location.search = $.param(queryParameters);
        }
    </script>
@stop