routes/web.php
<?php
use Illuminate\Support\Facades\Route;

if (version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}

Route::group(['prefix' => 'admin', 'namespace' => 'Backend', 'as' => 'admin.'], function() {
    Route::get('login', ['as' => 'login', 'uses' => 'HomeController@getLogin']);
    Route::group(['before' => 'csrf'], function() {
        Route::post('login', ['as' => 'login', 'uses' => "HomeController@postLogin"]);
    });
    Route::group(['middleware' => 'admin'], function() {
        Route::post('images/upload', ['as' => 'images.upload', 'role' => 'backend', 'uses' => 'HomeController@uploadImage']);
        Route::get('', ['as' => 'home', 'uses' => 'HomeController@index']);
        Route::post('get-district-by-province', ['as' => 'get-district-by-province', 'uses' => 'HomeController@getDistrictByProvince']);

        Route::resource('fixed-assets', 'FixedAssetController');
        Route::post('fixed-assets/add-cost-item', ['as' => 'storeCostItem', 'uses' => 'FixedAssetController@storeCostItem']);
        Route::resource('fixed-asset-depreciation', 'FixedAssetDepreciationController');
        Route::post('fixed-asset-depreciation/get-info', ['as' => 'depreciation-month-year', 'uses' => 'FixedAssetDepreciationController@getMonthYear']);
        Route::post('fixed-asset-depreciation/get-debit-object', ['as' => 'get-debit-object', 'uses' => 'FixedAssetDepreciationController@getDebitObject']);
        Route::post('fixed-asset-depreciation/get-credit-object', ['as' => 'get-credit-object', 'uses' => 'FixedAssetDepreciationController@getCreditObject']);
        Route::get('fixed-asset-depreciation/{id}/save', ['as' => 'fixed-asset-depreciation.to-save', 'uses' => 'FixedAssetDepreciationController@toSave']);
        Route::post('fixed-asset-depreciation/{id}/save', ['as' => 'fixed-asset-depreciation.save', 'uses' => 'FixedAssetDepreciationController@save']);
        Route::resource('fixed-asset-disposal', 'FixedAssetDisposalController');
        Route::post('fixed-asset-disposal/get-asset-info', ['as' => 'get-asset-info', 'uses' => 'FixedAssetDisposalController@getAssetInfo']);
        Route::resource('fixed-asset-reports', 'FixedAssetReportController');
        Route::post('fixed-asset-reports/get-report', ['as' => 'get-report', 'uses' => 'FixedAssetReportController@getReport']);
        Route::get('fixed-asset-reports-export', ['as' => 'fixed-asset-export', 'uses' => 'FixedAssetReportController@exportExcel']);
       
        Route::resource('expenses-prepaid', 'ExpensesPrepaidController');
        Route::post('expenses-prepaid/get-voucher', ['as' => 'get-vouchers', 'uses' => 'ExpensesPrepaidController@getVouchers']);
        Route::post('expenses-prepaid/edit-voucher', ['as' => 'edit-voucher', 'uses' => 'ExpensesPrepaidController@editVouchers']);
        Route::post('expenses-prepaid/check-code', ['as' => 'check-code', 'uses' => 'ExpensesPrepaidController@checkCode']);
        Route::post('expenses-prepaid/search-vouchers', ['as' => 'search-vouchers', 'uses' => 'ExpensesPrepaidController@searchVouchers']);
        Route::post('expenses-prepaid-allocation/get-info', ['as' => 'expenses-prepaid-allocation', 'uses' => 'ExpensesPrepaidAllocationController@getMonthYear']);
        Route::post('expenses-prepaid-allocation/get-debit-object', ['as' => 'get-debit-object', 'uses' => 'ExpensesPrepaidAllocationController@getDebitObject']);
        Route::post('expenses-prepaid-allocation/get-credit-object', ['as' => 'get-credit-object', 'uses' => 'ExpensesPrepaidAllocationController@getCreditObject']);
        Route::resource('expenses-prepaid-allocation', 'ExpensesPrepaidAllocationController');

        Route::resource('cost-items', 'CostItemController');
        
        Route::resource('instrument-tool-types', 'InstrumentToolTypeController');
        Route::resource('instrument-tools', 'InstrumentToolController');
        Route::resource('instrument-tool-allocation', 'InstrumentToolAllocationController');
        Route::resource('instrument-tool-disposal', 'InstrumentToolDisposalController');
        Route::post('instrument-tool-disposal/get-info', ['as' => 'get-instrument-tool-info', 'uses' => 'InstrumentToolDisposalController@getInfo']);
        Route::post('instrument-tool-allocation/get-info', ['as' => 'instrument-tool-allocation', 'uses' => 'InstrumentToolAllocationController@getMonthYear']);
        
        Route::post('instrument-tools/add-type', ['as' => 'storeType', 'uses' => 'InstrumentToolController@storeType']);
        Route::get('accounts/get-parents', ['as' => 'accounts.get-parents', 'role' => ['admin.accounts.view'], 'uses' => 'AccountsController@getParents']);
        Route::get('accounts/get-by-id', ['as' => 'accounts.get-by-id', 'role' => ['admin.accounts.update'], 'uses' => 'AccountsController@getById']);
        Route::get('accounts/get-by-group', ['as' => 'accounts.get-by-group', 'role' => ['admin.accounts.create', 'admin.accounts.update'], 'uses' => 'AccountsController@getByGroup']);
        Route::get('ajax-callback', ['as' => 'cb', 'role' => 'backend', 'uses' => 'AccountsController@CallbackDebtAccount']);
        Route::resource('accounts', 'AccountsController');
        Route::resource('jobs', 'JobsController');
        Route::resource('payment-receip-bank-report', 'PayReBankReportController');
        Route::get('payment-receipt-vouchers/{id}/edit-payment-vendor', ['as' => 'payment-receipt-vouchers.edit-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editPaymentVendor']);
        // Route::get('payment-receipt-vouchers/get-info-object-2', ['as' => 'payment-receipt-vouchers.get-info-object-2', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getInforObject2']);
        Route::get('payment-receipt-vouchers/create-payment-order-bank', ['as' => 'payment-receipt-vouchers.create-payment-order', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentOrder']);
        Route::get('payment-receipt-vouchers/create-receipt-bank', ['as' => 'payment-receipt-vouchers.create-receipt-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createReceiptBank']);
        Route::post('payment-receipt-vouchers/store-receipt-bank', ['as' => 'payment-receipt-vouchers.store-receipt-payment-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@storeReceiptPaymentBank']);
        Route::get('payment-receipt-vouchers/edit-receipt-payment-bank/{id}', ['as' => 'payment-receipt-vouchers.edit-receipt-payment-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editReceiptPaymentBank']);
        Route::put('payment-receipt-vouchers/update-receipt-bank/{id}', ['as' => 'payment-receipt-vouchers.update-receipt-bank', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@updateReceiptBank']);
        Route::put('payment-receipt-vouchers/update-payment-vendor/{id}', ['as' => 'payment-receipt-vouchers.update-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@updatePaymentVendor']);
        Route::post('payment-receipt-vouchers/get-voucher', ['as' => 'payment-receipt-vouchers.get-voucher', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getVoucher']);
        Route::get('payment-receipt-vouchers/{id}/edit-payment-vendor', ['as' => 'payment-receipt-vouchers.edit-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@editPaymentVendor']);
        Route::get('payment-receipt-vouchers/create-payment-vendor-step2', ['as' => 'payment-receipt-vouchers.create-payment-vendor-step2', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentVendorStep_2']);
        Route::post('payment-receipt-vouchers/store-payment-vendor', ['as' => 'payment-receipt-vouchers.store-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@storePaymentVendor']);
        Route::get('payment-receipt-vouchers/get-service-voucher', ['as' => 'payment-receipt-vouchers.get-service-voucher', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getServiceVoucher']);
        Route::get('payment-receipt-vouchers/create-payment-vendor', ['as' => 'payment-receipt-vouchers.create-payment-vendor', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@createPaymentVendorStep_1']);
        Route::post('payment-receipt-vouchers/delete_all', ['as' => 'payment-receipt-vouchers.delete_all', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@delete_all']);
        Route::get('payment-receipt-vouchers/get-info-object', ['as' => 'payment-receipt-vouchers.get-info-object', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@getInfoObject']);
        Route::get('payment-receipt-vouchers/create-receipt', ['as' => 'payment-receipt-vouchers.create-receipt', 'role' => 'backend', 'uses' => 'PaymentReceiptVouchersController@create_receipt']);
        Route::resource('payment-receipt-vouchers', 'PaymentReceiptVouchersController');
        Route::get('service-purchases/{id}/save', ['as' => 'service-purchases.save', 'role' => 'backend', 'uses' => 'ServicePurchasesController@save']); 
        Route::get('service-purchases/{id}/approve', ['as' => 'service-purchases.approve', 'role' => 'backend', 'uses' => 'ServicePurchasesController@approve']); 
        Route::get('service-purchases/{id}/cancel', ['as' => 'service-purchases.cancel', 'role' => 'backend', 'uses' => 'ServicePurchasesController@cancel']); 
        Route::get('service-purchases/get-info-sale-cost-item', ['as' => 'service-purchases.get-info-sale-cost-item', 'role' => 'backend', 'uses' => 'ServicePurchasesController@getInfoSaleCostItem']);
        Route::post('service-purchases/delete_all', ['as' => 'service-purchases.delete_all', 'role' => 'backend', 'uses' => 'ServicePurchasesController@delete_all']);
        Route::resource('service-purchases',"ServicePurchasesController");

app/Models/Report.php
<?php
namespace App;

class Report extends \Eloquent {

    public static function rules($id = 0) {
        return [
            'name'  => 'required|max:255',
            'slug'  => 'unique|max:100',
        ];
    }

    protected $fillable = ['name', 'slug', 'status'];

    public function roles()
    {
        return $this->belongsToMany("\App\Role", 'report_roles', 'report_id', 'role_id');
    }
}

app/Http/Controllers/Backend/BannerAdvertisementsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\BannerAdvertisement;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Controllers\Controller;

class BannerAdvertisementsController extends Controller
{
    public function index(Request $request)
    {
        $query = "1=1";
        $status = intval($request->input('status', -1));
        $type = trim($request->input('type'));
        if($status <> -1) $query .= " AND status = {$status}";
        if($type) $query .= " AND type = '{$type}'";
        $categories = BannerAdvertisement::whereRaw($query)->orderByRaw('updated_at DESC, type')->paginate(\App\Define\Constant::PAGE_NUM_20);
        return view('backend.banner-advertisements.index', compact('categories'));
    }

    public function create()
    {
        $types = \App\Define\Constant::getBannerTypes();
        return view('backend.banner-advertisements.create', compact('types'));
    }

    public function show($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'error');
            return redirect()->route('admin.banner-advertisements.index');
        }

        return view('backend.banner-advertisements.show', compact('category'));
    }

    public function edit($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'error');
            return redirect()->route('admin.banner-advertisements.index');
        }
        return view('backend.banner-advertisements.edit', compact('category'));
    }

    public function store(Request $request)
    {
        $request->merge(['status' => $request->input('status', 0)]);
        $validator = \Validator::make($data = $request->all(), BannerAdvertisement::rules());
        $validator->setAttributeNames(trans('banner_advertisements'));
        if ($validator->fails()) return back()->withErrors($validator)->withInput();
        $image  = $request->file('image');
        $ext    = pathinfo($image->getClientOriginalName(), PATHINFO_EXTENSION);
        $data['image'] = str_slug($data['name']) . '_' . time() . '.' . $ext;
        $image->move(config('upload.banner_advertisement'), $data['image']);
        $data['image'] = config('upload.banner_advertisement') . $data['image'];
        $data['created_by'] = $request->user()->id;
        BannerAdvertisement::create($data);
        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');

        return redirect()->route('admin.banner-advertisements.index');
    }

    public function update(Request $request, $id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'danger');
            return redirect()->route('admin.banner-advertisements.index');
        }
        $request->merge(['status' => $request->input('status', 0)]);
        $validator = \Validator::make($data = $request->all(), BannerAdvertisement::rules(intval($id)));//only(['status', 'name', 'seo_description', 'seo_keywords', 'image'])
        $validator->setAttributeNames(trans('banner_advertisements'));
        if ($validator->fails()) return back()->withErrors($validator)->withInput();

        if ($request->hasFile('image')) {
            if (\File::exists(public_path() . '/' . $category->image)) \File::delete(public_path() . '/' . $category->image);
            $image  = $request->file('image');
            $ext    = pathinfo($image->getClientOriginalName(), PATHINFO_EXTENSION);
            $data['image'] = str_slug($data['name']) . '_' . time(). '.' . $ext;
            $image->move(config('upload.banner_advertisement'), $data['image']);
            $data['image'] = config('upload.banner_advertisement') . $data['image'];
        }
        $category->update($data);
        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');

        return redirect()->route('admin.banner-advertisements.index');
    }

    public function destroy($id)
    {
        $category = BannerAdvertisement::find(intval($id));
        if (is_null($category)) {
            Session::flash('message', trans('system.have_an_error'));
            Session::flash('alert-class', 'danger');
            return redirect()->route('admin.banner-advertisements.index');
        }
        if (\File::exists(public_path() . '/' . $category->image)) \File::delete(public_path() . '/' . $category->image);
        $category->delete();

        Session::flash('message', trans('system.success'));
        Session::flash('alert-class', 'success');
        return redirect()->route('admin.banner-advertisements.index');
    }
}

app/Http/Controllers/Backend/DemoController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Exports\DemoExport;
use App\Bank;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Session;

class DemoController 
{
    public function index(Request $request)
    {
        $banks = Bank::all();
        // dd(count($data['banks']));
       
        // for($i = 1; $i <= count($users); $i++){
        // foreach ($users as $key => $value) {
                      
        //             $a[] = "{" . '"recid"' . ":" . $i++ . "," . ltrim(json_encode($value), "{");
        //     }  
        //     $records = implode(",", $a);

        // }
        return view('backend.demo.demo1', compact('banks'));   
    }
    public function getData(){
        $banks = Bank::all();
        
        $records = [];
        foreach ($banks as $key => $value) {
            $record = [
                'id' => $value->id, 'name'=> $value->name
            ];
            $records[] = $record;
        }
        $data = [   
            'total' => -1,          
            'records' => $records
        ];    
        return response($data);
    }
    public function dataExport(){
        $banks = Bank::all();
        $abc = [
            [
                [
                    'text' => 'ID'
                ],
                [
                    'text' => 'Name'
                ]
            ]

        ];
        foreach ($banks as $key => $value) {
            $record = [
                [
                    'text' => $value->id
                ],
                [
                    'text' => $value->name
                ]
            ];
            $abc[] = $record;
        }
        $tableData = [[
            'sheetName' => 'Sheet1',
            'data' => $abc
        ]];
        $data = [   
            'option' => ['filename' => 'Export'],          
            'tableData' => $tableData
        ];    
        return response($data);
    }
    public function exportExcel(){
        return Excel::download(new DemoExport, 'Demo.xlsx'); 
    }
}

resources/views/backend/reports/index.blade.php
@extends('backend.master')
@section('title')
{!! trans('reports.label') !!}
@stop
@section('head')
<link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/select2/select2.min.css') !!}" />
<link rel="stylesheet" type="text/css" href="{!! asset('assets/backend/plugins/daterangepicker/daterangepicker.css') !!}" />
<style type="text/css">
    .uppercase {
        text-transform: uppercase;
    }
</style>
@stop
@section('content')
<section class="content-header">
    <h1>
        {!! trans('reports.label') !!}
    </h1>
    <ol class="breadcrumb">
        <li><a href="{!! route('admin.home') !!}">{!! trans('system.home') !!}</a></li>
        <li><a href="{!! route('admin.reports.index') !!}">{!! trans('reports.label') !!}</a></li>
    </ol>
</section>
<section class="content overlay">
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
            	<div class="col-md-4">
                    {!! Form::label('type', trans('reports.label') ) !!}
            		<select class="form-control select2" name="type">
            			<option value="NONE">{!!  trans('reports.types.label') !!}</option>
            			@foreach ($types as $key => $name)
                            <option value="{!! $key !!}" @if(Request::input('type') == $key) selected @endif >{!! $name !!} - {!! $key !!}</option>
                        @endforeach
            		</select>
            	</div>
            	<div class="col-md-4">
                    <div class="form-group">
                        {!! Form::label('date_range', "Khoảng thời gian") !!}
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            {!! Form::text('date_range', Request::input('date_range', date('01/m/Y 00:00') . ' - ' . date('d/m/Y H:i')), ['class' => 'form-control pull-right date_range']) !!}
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        {!! Form::label('filter', trans('system.action.label'), ['style' => 'width: 100%;']) !!}
                        <button type="submit" class="btn btn-info" id="report">
                            <span class="glyphicon glyphicon-flash"></span>&nbsp; Lập báo cáo
                        </button>
                    </div>
                </div>
            	<div class="col-md-2">
                    <div class="form-group">
                        {!! Form::label('filter', trans('system.action.label'), ['style' => 'width: 100%;']) !!}
                    	<button type="button"  class="btn btn-success" onclick="window.open('{!! route('admin.reports.export', ['type' => 'excel']) !!}')">
                    		<span class="far fa-file-excel fa-fw"></span>&nbsp; Xuất excel
                    	</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box">
        <div class="box-body no-padding">
            <div id="result" class="table-responsive">
            </div>
        </div>
    </div>
</section>
@stop
@section('footer')
<script src="{!! asset('assets/backend/plugins/select2/select2.full.min.js') !!}"></script>
<script src="{!! asset('assets/backend/plugins/daterangepicker/moment.min.js') !!}"></script>
<script src="{!! asset('assets/backend/plugins/daterangepicker/daterangepicker.js') !!}"></script>
<script>
    !function ($) {
        $(function(){
            $(".select2").select2({ width: '100%' });
            $('.date_range').daterangepicker({
                autoUpdateInput: false,
                "locale": {
                    "format": "DD/MM/YYYY HH:mm",
                    "separator": " - ",
                    "applyLabel": "Áp dụng",
                    "cancelLabel": "Huỷ bỏ",
                    "fromLabel": "Từ ngày",
                    "toLabel": "Tới ngày",
                    "customRangeLabel": "Tuỳ chọn",
                    "weekLabel": "W",
                    "daysOfWeek": [
                        "CN",
                        "T2",
                        "T3",
                        "T4",
                        "T5",
                        "T6",
                        "T7"
                    ],
                    "monthNames": [
                        "Thg 1",
                        "Thg 2",
                        "Thg 3",
                        "Thg 4",
                        "Thg 5",
                        "Thg 6",
                        "Thg 7",
                        "Thg 8",
                        "Thg 9",
                        "Thg 10",
                        "Thg 11",
                        "Thg 12"
                    ],
                    "firstDay": 1
                },
                ranges: {
                   'Hôm nay': [moment(), moment()],
                   'Hôm qua': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                   '7 ngày trước': [moment().subtract(6, 'days'), moment()],
                   '30 ngày trước': [moment().subtract(29, 'days'), moment()],
                   'Tháng này': [moment().startOf('month'), moment()],
                   'Tháng trước': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                },
                "alwaysShowCalendars": true,
                maxDate: moment(),
                minDate: moment().subtract(1, "years"),
            }, function(start, end, label) {
                $('.date_range').val(start.format('DD/MM/YYYY HH:mm') + " - " + end.format('DD/MM/YYYY HH:mm'));
            });
            $(".product_model").hide();
            $(".product_name").hide();
            $(".product_in_stock").hide();
            $(".product_price").hide();

            $("select[name='type']").change(function(event) {
                $('#result').html('');
                //$("#date_label").html('').append('Từ ngày');

                // $("input[name='product_model']").val('');
                // $("input[name='product_name']").val('');
                // $("select[name='product_in_stock_operator']").val(">=");
                // $("input[name='product_in_stock']").val(0);
                // $("select[name='product_price_operator']").val(">=");
                // $("input[name='product_price']").val(0);

                switch($(this).val()) {
                    case "{!! \App\Define\Report::ORDER_CPN !!}":
                    case "{!! \App\Define\Report::ORDER_BANK_NL !!}":
                    case "{!! \App\Define\Report::ORDER_ALL !!}":
                        //$("#date_label").html('').append('Ngày tạo đơn hàng từ ngày');
                        // $(".product_model").show();
                        // $(".product_name").show();
                        // $(".product_in_stock").hide();
                        // $(".product_price").show();
                        break;
                    default:
                        // $(".product_model").hide();
                        // $(".product_name").hide();
                        // $(".product_in_stock").hide();
                        // $(".product_price").hide();
                        toastr.warning('Bạn cần chọn 1 loại báo cáo.');
                }
            });

            $("#report").click(function(event) {
                var type = $("select[name='type']").val();
                if( type == 'NONE' ) {
                    toastr.warning("Bạn cần chọn 1 loại báo cáo.")
                    return false;
                }


                NProgress.start();
                $.ajax({
                    url: "{!! route('admin.reports.store') !!}",
                    type: 'POST',
                    headers: {'X-CSRF-Token': "{!! csrf_token() !!}"},
                    data: { type: type, date_range: $(".date_range").val(), product_model: $("input[name='product_model']").val(), product_name: $("input[name='product_name']").val(), product_in_stock_operator: $("select[name='product_in_stock_operator']").val(), product_in_stock: $("input[name='product_in_stock']").val(), product_price_operator: $("select[name='product_price_operator']").val(), product_price: $("input[name='product_price']").val() },
                    datatype: 'json',
                    success: function(data) {
                        if (data.error) {
                            toastr.warning(data.message);
                        } else {
                            $('#result').html('').append(data.message);
                        }
                    },
                    error: function(obj, status, err) {
                        var error = $.parseJSON(obj.responseText);
                        toastr.warning(error.message);
                    }
                }).always(function() {
                    NProgress.done();
                });
            });
        });
}(window.jQuery);

</script>
@stop